apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-demo.selectorLabels" . | nindent 4 }}
