# Default values for app-demo.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: docker.hub/demo-app
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

labels:
  app: demo-app
  environment: test

metadata:
  name: demo-app

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: demo.local
      paths:
        - path: /
  tls: 
    - secretName: name-tls
      hosts:
        - demo.local

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  host: redis.database.svc.cluster.local
  port: "6379"
postgres:
  host: postgres.database.svc.cluster.local
  port: "5432"
  user: postgres
  password: password
  database: mydatabase